name: Close Issues on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Extract issue numbers from PR body
        id: extract_issue
        run: |
          echo "Extracting issue numbers..."
          ISSUE_NUMBERS=$(echo "${{ github.event.pull_request.body }}" | grep -o '#[0-9]\+' | tr -d '#')
          if [ -z "$ISSUE_NUMBERS" ]; then
            echo "No issues referenced in the PR body."
          else
            echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          fi

      - name: Close referenced issues
        if: ${{ env.ISSUE_NUMBERS != '' }}
        run: |
          for issue in $ISSUE_NUMBERS; do
            echo "Closing issue: $issue"
            gh issue close $issue --comment "Automatically closed because the related pull request has been merged."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
